version: '3'
services:
 mysql:
   image: mysql:5.7
   container_name: dummy-mysql
   ports:
     - 3306:3306
   volumes:
     - ./mysql_data:/var/lib/mysql
   environment:
     MYSQL_ROOT_PASSWORD: mysql
     MYSQL_DATABASE: nestjs-typeorm
     MYSQL_USER: user
     MYSQL_PASSWORD: password
